language: node_js
node_js: lts/*
cache:
  directories:
  - node_modules
script:
- cd test-app
- npm install
- npm test
- npm run build
deploy:
  provider: firebase
  token:
    secure: IdXaUhVD+6QjADnu6i+wWvyRgR3musI0jrBniBiJKlfYdT5y1XOUxLWoK74a5aLFvcC402VzX2AGMgP4s+f7ZteJHi+nHjxAfdP/A1HQ1uEM8TMMOu0PPMt/KjqGdbXbg6isj9D3w3KM97mbQ6mDutKHpVOe2SJgKXT3Sm2Yb9HwOVJjc1NY0zuMZ7Dv96EKmQX6bADiHu8Q/c44n4lIcAe/imQCnW5fMa9qr0SgEhfqa2StuhyelADmw+ZsxBIHFneZuslCgSiBcjMWf64ICGmrYmp54FN9zBHBBBpHJdI2TQU4srft3bOIHZkmVfQIbAwswc2TLSL9317v2wsCXBa98EmpqMOlem/j3c4NgmZTVSz5CopPQFYpnv/JkvB7ijcc0jFAMFkXrhWr/I+xthc6Ypv5GSFzojxnylbqGXgvlQDIkMjn1OI4I+n0WSVh3zjhmHkX5+IC2e65YgI4tTIeTVZcQvWcbBam0GknMOBfvISQbex7aHOnnearJXLFhcZVCim2uJNoPCHjdiPgyNv1aVMfUT56BcwQFbV4flhwyb/czNhLESOPFRrSMLOTC24sUeUpasBofy1ax1v+4v25r+bL8a55bbGXrmqg4MCxoEyoll0A/QGBt/Ru87BJGu9V61Kj2to2/FOD/4lefuLbGkVsFBOvfpT+NIWG2Fg=
env:
  global:
    secure: IdXaUhVD+6QjADnu6i+wWvyRgR3musI0jrBniBiJKlfYdT5y1XOUxLWoK74a5aLFvcC402VzX2AGMgP4s+f7ZteJHi+nHjxAfdP/A1HQ1uEM8TMMOu0PPMt/KjqGdbXbg6isj9D3w3KM97mbQ6mDutKHpVOe2SJgKXT3Sm2Yb9HwOVJjc1NY0zuMZ7Dv96EKmQX6bADiHu8Q/c44n4lIcAe/imQCnW5fMa9qr0SgEhfqa2StuhyelADmw+ZsxBIHFneZuslCgSiBcjMWf64ICGmrYmp54FN9zBHBBBpHJdI2TQU4srft3bOIHZkmVfQIbAwswc2TLSL9317v2wsCXBa98EmpqMOlem/j3c4NgmZTVSz5CopPQFYpnv/JkvB7ijcc0jFAMFkXrhWr/I+xthc6Ypv5GSFzojxnylbqGXgvlQDIkMjn1OI4I+n0WSVh3zjhmHkX5+IC2e65YgI4tTIeTVZcQvWcbBam0GknMOBfvISQbex7aHOnnearJXLFhcZVCim2uJNoPCHjdiPgyNv1aVMfUT56BcwQFbV4flhwyb/czNhLESOPFRrSMLOTC24sUeUpasBofy1ax1v+4v25r+bL8a55bbGXrmqg4MCxoEyoll0A/QGBt/Ru87BJGu9V61Kj2to2/FOD/4lefuLbGkVsFBOvfpT+NIWG2Fg=
